"""
server/app.py — FastAPI application for IncidentCommander OpenEnv.

Uses the official openenv HTTP server factory (create_app) to generate
all required endpoints (/reset, /step, /state, /schema, /ws) and adds
the /tasks endpoint required by the Phase 2 hackathon validator.

Endpoints (auto-generated by create_app):
  POST /reset   → ResetResult
  POST /step    → StepResult
  GET  /state   → State
  GET  /schema  → action/observation schemas
  WS   /ws      → WebSocket persistent session

Additional endpoints:
  GET  /tasks   → List of tasks with grader paths (required by validator)
  GET  /health  → {"status": "ok"}

Usage:
  uvicorn server.app:app --host 0.0.0.0 --port 7860
"""

import sys
import os

# Ensure root directory is on sys.path so top-level modules are importable
_server_dir = os.path.dirname(os.path.abspath(__file__))
_root_dir = os.path.dirname(_server_dir)
if _root_dir not in sys.path:
    sys.path.insert(0, _root_dir)

try:
    from openenv.core.env_server.http_server import create_app
except Exception as e:  # pragma: no cover
    raise ImportError(
        "openenv is required. Install dependencies with:\n    uv sync\n"
        "or:\n    pip install openenv-core[core]>=0.2.2"
    ) from e

from fastapi.responses import RedirectResponse
from models import IncidentCommanderAction, IncidentCommanderObservation
from server.environment import IncidentCommanderEnvironment
from server.gradio_ui import build_ui
import gradio as gr

# ---------------------------------------------------------------------------
# Create the OpenEnv-compatible FastAPI app
# ---------------------------------------------------------------------------

app = create_app(
    IncidentCommanderEnvironment,
    IncidentCommanderAction,
    IncidentCommanderObservation,
    env_name="incident_commander",
    max_concurrent_envs=25,
)

# ---------------------------------------------------------------------------
# Root Redirect and Dashboard Mounting
# ---------------------------------------------------------------------------

@app.get("/", include_in_schema=False)
async def root_redirect():
    """Redirect root to the interactive dashboard."""
    return RedirectResponse(url="/ui")

# Mount Gradio at /ui to avoid conflicts with API root routes
app = gr.mount_gradio_app(app, build_ui(), path="/ui")


# ---------------------------------------------------------------------------
# /tasks endpoint — required by the Phase 2 deep validator
# ---------------------------------------------------------------------------

@app.get("/tasks", tags=["Environment Info"], summary="List all tasks with graders")
async def list_tasks():
    """Return the list of available tasks, their difficulties, and grader info."""
    return [
        {
            "id": "easy",
            "name": "Single-Service Failure",
            "description": (
                "Identify a single failing service from clear error logs "
                "and recommend the correct fix."
            ),
            "difficulty": "easy",
            "time_limit_seconds": 300,
            "max_steps": 3,
            "grader": "server.graders.grade_easy",
            "action_schema": {
                "response": (
                    "Free-text incident analysis identifying the failing service, "
                    "root cause, and recommended actions."
                ),
            },
        },
        {
            "id": "medium",
            "name": "Multi-Signal Failure with Red Herrings",
            "description": (
                "Identify the true root cause among misleading signals. "
                "Explicitly flag the red herring with dismissal language."
            ),
            "difficulty": "medium",
            "time_limit_seconds": 600,
            "max_steps": 3,
            "grader": "server.graders.grade_medium",
            "action_schema": {
                "response": (
                    "Free-text analysis that identifies root cause AND explicitly "
                    "calls out the red herring (e.g. 'Signal X is a red herring')."
                ),
            },
        },
        {
            "id": "hard",
            "name": "Cascading Infrastructure Failure",
            "description": (
                "Diagnose a cascading multi-service P0 outage and provide a "
                "FIRST / SECOND / THIRD prioritized remediation plan with reasoning."
            ),
            "difficulty": "hard",
            "time_limit_seconds": 900,
            "max_steps": 3,
            "grader": "server.graders.grade_hard",
            "action_schema": {
                "response": (
                    "Structured incident analysis with explicit FIRST/SECOND/THIRD "
                    "prioritized remediation steps explaining causal ordering."
                ),
            },
        },
    ]


# ---------------------------------------------------------------------------
# /health endpoint — liveness probe
# ---------------------------------------------------------------------------

@app.get("/health", tags=["Health"])
async def health():
    """Health check — returns 200 when the server is up."""
    return {
        "status": "ok", 
        "environment": "incident_commander", 
        "version": "1.0.0",
        "ui_path": "/ui"
    }


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main(host: str = "0.0.0.0", port: int = 7860):
    """
    Entry point for direct execution or uv run.
        uvicorn server.app:app --host 0.0.0.0 --port 7860
        python -m server.app
    """
    import uvicorn
    uvicorn.run(app, host=host, port=port)


if __name__ == "__main__":
    main()
